// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJu2p8RxYYnkh_4MnbaA_2Kn4KAI59Hk',
    appId: '1:67409304255:web:1126bb99e55a42097b840a',
    messagingSenderId: '67409304255',
    projectId: 'to-do-app-practice-97457',
    authDomain: 'to-do-app-practice-97457.firebaseapp.com',
    storageBucket: 'to-do-app-practice-97457.firebasestorage.app',
    measurementId: 'G-KVM558HS0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNPJ59mLsuX3OdT5lsPND6WPt7OfdjuYI',
    appId: '1:67409304255:android:3071bdf4b2a408a47b840a',
    messagingSenderId: '67409304255',
    projectId: 'to-do-app-practice-97457',
    storageBucket: 'to-do-app-practice-97457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPKm012WZ-21ZSltmxqMEO3BNeuG0oXUM',
    appId: '1:67409304255:ios:4cf043a1424f791c7b840a',
    messagingSenderId: '67409304255',
    projectId: 'to-do-app-practice-97457',
    storageBucket: 'to-do-app-practice-97457.firebasestorage.app',
    iosBundleId: 'com.example.stateManagementPractice',
  );
}
